@startuml
state AcquireRelease{
  [*] -> Start
  state Start #green
  state Acquired #yellow : task : int\nlock : int
  Start --> Acquired : **Acquire({'task': task, 'lock': lock})**\n--->\n(task,lock)
  state error #red
  Acquired --> error : 1 **Acquire({'lock': self.lock})**
  Acquired --> [*] : 2 **Release({'task': self.task, 'lock': self.lock})**
}
@enduml