@startuml
state OrderProcessingMonitor{
  state error #red
  [*] -> OrderReceived
  state OrderReceived

  state PaymentProcessing #yellow

  state Shipping

  OrderReceived --> PaymentProcessing : **event**\nevent.name == 'process'
  PaymentProcessing --> Shipping : **payment_complete**
  OrderReceived --> [*] : **event**\nevent.name == 'validate' and\nevent.value > 0
  state error #red
  OrderReceived --> error : **event**\nevent.name == 'validate' and\n__not__(event.value > 0)
  PaymentProcessing --> [*] : **event**\nevent.name == 'payment_complete'
  PaymentProcessing --> OrderReceived : **event**\n__not__(event.name == 'payment_complete') and\nevent.name == 'payment_failed'
  Shipping --> [*] : **event**\nevent.name == 'shipped' and\nevent.value == 'success'
  state error #red
  Shipping --> error : **event**\nevent.name == 'shipped' and\n__not__(event.value == 'success')
}
@enduml
