@startuml
hide empty description
state PaymentMonitor{
  state error #red
  [*] -> Idle
  state Idle

  state OR <<choice>>

  state SmallTransfer : amount : int, destination : Any

  state LargeTransfer : amount : int, destination : Any

  Idle --> OR : **event**\nevent is TransferEvent
  OR -[dashed]-> SmallTransfer : \n--->\n(event.amount,event.destination)
  OR -[dashed]-> LargeTransfer : \n--->\n(event.amount,event.destination)
  SmallTransfer --> [*] : **event**\nself.amount < 1000 and\nevent.name == 'approve'
  SmallTransfer --> Idle : **event**\nself.amount < 1000 and\n__not__(event.name == 'approve') and\nevent.name == 'reject'
  state error #red
  SmallTransfer --> error : **event**\n__not__(self.amount < 1000)
  LargeTransfer --> [*] : **event**\nself.amount >= 1000 and\nevent.name == 'approve_by_manager'
  LargeTransfer --> Idle : **event**\nself.amount >= 1000 and\n__not__(event.name == 'approve_by_manager') and\nevent.name == 'reject'
  state error #red
  LargeTransfer --> error : **event**\n__not__(self.amount >= 1000)
}
@enduml
