@startuml
hide empty description
state RoverMonitor{
  [*] -> __Always__
  state __Always__ #green

  state Idle #yellow

  state TransitMode #yellow

  state SafetyMode #yellow

  state Imaging #yellow

  state DataCollection #yellow

  state Driving #yellow

}
@enduml
