@startuml
hide empty description
state AndStateMonitor{
  [*] -> __Always__
  state __Always__ #green

  state fork_state1 <<fork>>

  state Imaging #yellow

  state DataCollection #yellow

  __Always__ --> fork_state1 : **event**
  fork_state1 -[dashed]-> Imaging
  fork_state1 -[dashed]-> DataCollection
  Imaging --> __Ok__ : **event**\nTakePicture()
  DataCollection --> __Ok__ : **event**\nCollectSample()
}
@enduml
