@startuml
hide empty description
state NotStateMonitor{
  [*] -> __Always__
  state __Always__ #green

  state NOT <<circle>> #black

  state Driving #yellow

  state Communicating #yellow

  state AND_INNER <<fork>>

  __Always__ --> NOT : **event**
  NOT -[dashed]-> AND_INNER
  AND_INNER -[dashed]-> Driving
  AND_INNER -[dashed]-> Communicating
}
@enduml
