@startuml
hide empty description
state OrStateMonitor{
  [*] -> __Always__
  state __Always__ #green

  state OR <<choice>>

  state SciencePath #yellow

  state TransitPath #yellow

  __Always__ --> OR : **event**
  OR -[dashed]-> SciencePath
  OR -[dashed]-> TransitPath
  SciencePath --> __Ok__ : **event**\nTakePicture()
  SciencePath --> __Ok__ : **event**\nCollectSample()
  TransitPath --> __Ok__ : **event**\nDrive()
  TransitPath --> __Ok__ : **event**\nStop()
}
@enduml
